### ISSUE TITLE
Is it possible to increase the vertical animation space for the digits?

### ISSUE THREAD

**Issue by alguintu** [h65wang/flutter-animated-counter#12]
Currently, the digits animate up and down exactly at the edge of the text height.  I would like to increase the space that the digits move in to fit the vertical space in the container it is in.

![image](https://user-images.githubusercontent.com/6581480/182999388-71864d26-b4e9-4bd2-964d-4a94bb475072.png)

Is there a way to adjust this? Thanks.

**Comment by alguintu** [comment]
Submitted [PR #13](https://github.com/h65wang/flutter-animated-counter/pull/13) as a solution.

**Comment by h65wang** [comment]
Thank you very much for your PR. I've released v0.2.5 please take a look: https://pub.dev/packages/animated_flip_counter/changelog

For your use case, you can set something like `padding: EdgeInsets.symmetric(vertical: 8)`.

**Comment by alguintu** [comment]
Thank you! Moved back to official repo to test and it works, although had to change a little bit in my code to compute for the effect of height + padding since I'm doing some other animations. Works perfectly to my use case now!
