### ISSUE TITLE
Pause / get current value

### ISSUE THREAD

**Issue by okandemirofficial** [h65wang/flutter-animated-counter#14]
Hello!
 
I have an intention to make a scoreboard with this package.  I am curious about whether is it possible to pause and get the current value.

Let's say I set the duration to 40 seconds and, the user clicked the pause button after 20 seconds. I would like to stop the animation and get the last rendered value. I looked for the controller but couldn't find it.

Thanks in advance!

**Comment by h65wang** [comment]
You should store timer data in a variable separate from UI.
