### ISSUE TITLE
What about different fonts?

### ISSUE THREAD

**Issue by ivofernandes** [h65wang/flutter-animated-counter#15]
I found a bug with the size with different fonts, what if was possible to override the size of number? I could make that pull request if is a bug that more people have, I guess I will need to fix it anyway for my company app

```
_SingleDigitFlipCounter(
              key: ValueKey("decimal$i"),
              value: digits[i].toDouble(),
              duration: duration,
              curve: curve,
              size: digitSize ? digitSize : prototypeDigit.size,
              color: color,
              padding: padding,
            ),
```

**Comment by h65wang** [comment]
The size is already measured with a prototype, so it should adjust to different fonts. Could you post a screenshot of the issue, and possibly the name of the font? Also, does changing the `padding` help? Thanks.

**Comment by ivofernandes** [comment]
Looks like the problem is with line heights and not the font itself, will try to fork and share the example 

![Screenshot_20221012_161445_com.example.example.jpg](https://user-images.githubusercontent.com/606568/195381508-6f0edcd8-7114-45ae-9d79-4e67287590f8.jpg)

**Comment by ivofernandes** [comment]
Created here a branch with an example of the bug and fix
https://github.com/ivofernandes/flutter-animated-counter

For short, the problem is with the line height, for that I created a text style

```
    TextStyle textStyle = TextStyle(
      fontWeight: FontWeight.w700,
      fontSize: 16,
      height: 22 / 26,
    );
```

Then this code is an example of the problem and how it's possible to solve:
```
Text(
              'Example: Prefix 10 Suffix',
              style: textStyle,
            ),
            MaterialButton(
              shape: const RoundedRectangleBorder(
                borderRadius: BorderRadius.all(
                  Radius.circular(10),
                ),
              ),
              elevation: 10,
              onPressed: () => setState(() {
                _value++;
              }),
              color: Colors.green,
              child: Padding(
                padding: const EdgeInsets.symmetric(vertical: 11),
                child: AnimatedFlipCounter(
                  textStyle: textStyle,
                  prefix: 'Prefix ',
                  suffix: ' Suffix',
                  value: _value,
                ),
              ),
            ),
            Text('fixed:'),
            MaterialButton(
              shape: const RoundedRectangleBorder(
                borderRadius: BorderRadius.all(
                  Radius.circular(10),
                ),
              ),
              elevation: 10,
              onPressed: () => setState(() {
                _value++;
              }),
              color: Colors.green,
              child: Padding(
                padding: const EdgeInsets.symmetric(vertical: 11),
                child: AnimatedFlipCounter(
                  digitSize: Size(15, 17),
                  textStyle: textStyle,
                  prefix: 'Prefix ',
                  suffix: ' Suffix',
                  value: _value,
                ),
              ),
            ),
```

**Comment by ivofernandes** [comment]
So it's looking like this the example in my fork,I can do a pull request if is something you would like to have in the main branch, and I can update the example to only have the part that works fine, or should this problem have a different solution? ![Screenshot_20221012_162539_com.example.example.jpg](https://user-images.githubusercontent.com/606568/195384512-eb618131-181b-4ae7-8395-ad91fa17f6bc.jpg)

**Comment by ivofernandes** [comment]
Maybe there is a more elegant way of dealing with this problem? By the way, that package example is really well done, congrats, made my life much easier to have such a great example app :)

**Comment by ivofernandes** [comment]
Oh wait, there is an easier fix, when you calculate the size you just need to put a copy with and reset the line height to 1, maybe that's a more elegant solution

```final prototypeDigit = TextPainter(
      text: TextSpan(
          text: "8",
          style: style.copyWith(
            height: 1,
          )),
      textDirection: TextDirection.ltr,
      textScaleFactor: MediaQuery.of(context).textScaleFactor,
    )..layout();
```
