### ISSUE TITLE
Add support for thousand separator

### ISSUE THREAD

**Issue by ariona** [h65wang/flutter-animated-counter#2]
Current version not supported for thousand separator, only decimal separator present.

**Comment by h65wang** [comment]
Thanks for the suggestion.

Version 0.2.1 added `thousandSeparator` property. E.g. `thousandSeparator: ','` turns `1000` into `1,000`.

For certain locale, we can customize the `thousandSeparator` and `decimalSeparator` so `1,000.48` becomes `1.000,48`. 

Please help test these features and let me know how it goes.

**Comment by ariona** [comment]
Thanks for the update,  it's working 👍
