### ISSUE TITLE
feature request: animate to compact number format

### ISSUE THREAD

**Issue by e200** [h65wang/flutter-animated-counter#20]
Goal: Instead of Animate from 999 to 1000, animate from 999 to 1k, 1k to 2k, and so on... as the Youtube counter does.

Is it possible?

**Comment by h65wang** [comment]
This can be somewhat achieved by adjusting what values are fed into the widget. For example:

```
AnimatedFlipCounter(
  value: _value < 1000 ? _value : _value ~/ 1000,
  suffix: _value < 1000 ? '' : 'K',
)
```
