### ISSUE TITLE
Spacing issue with specific font

### ISSUE THREAD

**Issue by esentis** [h65wang/flutter-animated-counter#23]
This issue must be similar to #7 & #6 . While using [CeraPro](https://www.downloadfonts.io/download/cera-pro/) font and stacking `AnimatedFlipCounter` with a `Text` with similar values I'm getting below result :

<img width="175" alt="Screenshot 2024-01-03 at 3 11 33 PM" src="https://github.com/h65wang/flutter-animated-counter/assets/52862600/316fc1c4-52a0-426c-8e43-010521fe381b">

Below is the code for this :

```dart
Stack(
  children: [
    const AnimatedFlipCounter(
      duration: Duration(milliseconds: 1200),
      curve: Curves.elasticInOut,
      value: 129,
      thousandSeparator: '.',
      mainAxisAlignment: MainAxisAlignment.start,
      textStyle: TextStyle(
        color: Colors.black,
        fontSize: 45,
        fontFamily: 'CeraPro',
        ),
      fractionDigits: 2,
     ),
     Text(
      '129.00',
       style: TextStyle(
        color: Colors.red.withOpacity(0.5),
        fontSize: 45,
        fontFamily: 'CeraPro',
       ),
      ),
   ],
),
 ```
 
Changing the font family to e.g `Arial` doesn't reproduce the issue.  Is there any workaround for non mono spaced fonts ? Using `FontFeature.tabularFigures()` doesn't change anything. The issue is present for any number starting with "1". If I change the number to anything that does not start with 1, the spacing is not there, besides the spacing of the fractions. 

![Screenshot 2024-01-03 at 3 38 49 PM](https://github.com/h65wang/flutter-animated-counter/assets/52862600/f636d4c7-a177-4c4f-8f4c-b626b7f69587)

**Comment by h65wang** [comment]
A request to use `FontFeature.tabularFigures` has been added to v0.3.1. Hopefully this can help resolve alignment issues for fonts that support tabular figures.
