### ISSUE TITLE
垂直方向错位

### ISSUE THREAD

**Issue by zysc8313** [h65wang/flutter-animated-counter#3]
你好
前缀是中文时候，垂直方向有错位

```
AnimatedFlipCounter(
  value: 100,
  prefix: '中文: ',
  textStyle: TextStyle(
    fontSize: 10.0,
  ),
);
```

**Comment by h65wang** [comment]
Cannot reproduce.

![demo](https://user-images.githubusercontent.com/41172064/151419687-be0cb31a-053c-4a86-981b-4c664e55142d.png)

Code:

    AnimatedFlipCounter(
      value: 100,
      prefix: '中文: ',
      textStyle: TextStyle(
        fontSize: 10.0,
      ),
    ),
    AnimatedFlipCounter(
      value: _value,
      prefix: "中文：",
      textStyle: TextStyle(
        fontSize: 80,
        fontWeight: FontWeight.bold,
        letterSpacing: -8.0,
        color: Colors.yellow,
        shadows: [
          BoxShadow(
            color: Colors.orange,
            offset: Offset(2, 4),
            blurRadius: 4,
          ),
        ],
      ),
    ),

**Comment by zysc8313** [comment]
你可以把字体放小，在外面套个有颜色的Container会更容易发现问题


<img width="319" alt="WX20220128-124312@2x 2" src="https://user-images.githubusercontent.com/18691243/151490478-6e5d94e6-1ffb-457f-8705-bcff3d17a77f.png">


<img width="198" alt="WX20220128-124414@2x 2" src="https://user-images.githubusercontent.com/18691243/151490479-1bab72f9-2b36-40df-a1fa-2ab9cf754177.png">

**Comment by h65wang** [comment]
你用的是10号字，我上面回复也用的10号字。我再给你加一个红色的Container试试：

<img width="66" alt="image" src="https://user-images.githubusercontent.com/41172064/155396233-f9a4db2f-8d8b-4915-a4e1-01e58d9e4b31.png">


```
  Container(
    color: Colors.red,
    child: AnimatedFlipCounter(
      value: 100,
      prefix: '中文: ',
      textStyle: TextStyle(
        fontSize: 10.0,
      ),
    ),
  ),
```

还是无法复刻，可能是你的字体或者平台问题，比如安卓上经常会有Flutter中文字无法对齐的情况，不是插件的问题。
