### ISSUE TITLE
text value spacing issue

### ISSUE THREAD

**Issue by husnain067** [h65wang/flutter-animated-counter#6]
AnimatedFlipCounter(
                              curve: Curves.slowMiddle,
                              value: price,
                              fractionDigits: 2, // decimal precision
                              textStyle: const TextStyle(
                                letterSpacing: -4.0,
                                wordSpacing: 0.0,
                                color: simpleTextColor,
                                fontWeight: FontWeight.w700,
                                fontSize: 32.0,
                              ),
                            ),

**Comment by husnain067** [comment]
![image](https://user-images.githubusercontent.com/52630357/155311985-efc3ba6e-1fc7-4513-8812-33f200cfbc54.png)

**Comment by husnain067** [comment]
> ![image](https://user-images.githubusercontent.com/52630357/155311985-efc3ba6e-1fc7-4513-8812-33f200cfbc54.png)

extra space before 1 this creating the issue

**Comment by h65wang** [comment]
Cannot reproduce with your code.

<img width="148" alt="image" src="https://user-images.githubusercontent.com/41172064/155399129-2842a82b-80f6-4b82-9f9b-685895543a8a.png">


    AnimatedFlipCounter(
      curve: Curves.slowMiddle,
      value: 2333.33,
      fractionDigits: 2, // decimal precision
      textStyle: const TextStyle(
        letterSpacing: -4.0,
        wordSpacing: 0.0,
        color: Colors.red,
        fontWeight: FontWeight.w700,
        fontSize: 32.0,
      ),
    ),

**Comment by h65wang** [comment]
This is intended. Each digit has a fixed width, to avoid jumping around when values are changed.

<img width="85" alt="image" src="https://user-images.githubusercontent.com/41172064/155400017-cc4350a6-2ce9-44d5-9e5f-e540980e6559.png">

It's the `1` that makes it look like there's extra space.

<img width="82" alt="image" src="https://user-images.githubusercontent.com/41172064/155399935-b29b7539-a477-4a2a-ba36-a3ceebd30b01.png">

**Comment by h65wang** [comment]
It's worth adding that, using a monospaced font can be a valid workaround, see [this issue](https://github.com/h65wang/flutter-animated-counter/issues/7#issuecomment-1057210559).

**Comment by h65wang** [comment]
Oops, turns out this could be caused by a bug. I just released a fix in `v0.2.4`, please help test and report if your issue has been resolved. Thanks!

**Comment by SimonVillage** [comment]
I have seen that you use this for spacing
```dart
    final prototypeDigit = TextPainter(
      text: TextSpan(text: "8", style: style),
      textDirection: TextDirection.ltr,
      textScaleFactor: MediaQuery.of(context).textScaleFactor,
    )..layout();
```

I think it would be better to use
```dart
  style: TextStyle(
    fontFeatures: [
      FontFeature.tabularFigures()
    ],
  ),
```

https://api.flutter.dev/flutter/dart-ui/FontFeature/FontFeature.tabularFigures.html

**Comment by husnain067** [comment]
> I have seen that you use this for spacing
> 
> ```dart
>     final prototypeDigit = TextPainter(
>       text: TextSpan(text: "8", style: style),
>       textDirection: TextDirection.ltr,
>       textScaleFactor: MediaQuery.of(context).textScaleFactor,
>     )..layout();
> ```
> 
> I think it would be better to use
> 
> ```dart
>   style: TextStyle(
>     fontFeatures: [
>       FontFeature.tabularFigures()
>     ],
>   ),
> ```
> 
> https://api.flutter.dev/flutter/dart-ui/FontFeature/FontFeature.tabularFigures.html

@h65wang what about this solution

**Comment by h65wang** [comment]
A request to use `FontFeature.tabularFigures` has been added to v0.3.1. Hopefully this can help resolve alignment issues for fonts that support tabular figures.
