### ISSUE TITLE
the digit "1" has a weird formatting

### ISSUE THREAD

**Issue by yuhao-nyc** [h65wang/flutter-animated-counter#7]
It seems like an extra space was added on the right of "1" 🤔 
Check below the space between 1 and 9
<img width="79" alt="Screen Shot 2022-03-02 at 12 38 05 PM" src="https://user-images.githubusercontent.com/4121735/156417163-ce4df851-6d73-415a-bb3c-23df0f44abd8.png">

**Comment by h65wang** [comment]
Yeah, this is due to the font choices. Try a [monospaced font](https://en.wikipedia.org/wiki/Monospaced_font) like [`Courier`](https://en.wikipedia.org/wiki/Courier_(typeface)) and it should be okay.

For example:

```
AnimatedFlipCounter(
  value: 1818,
  duration: Duration(seconds: 1),
  curve: Curves.bounceOut,
  textStyle: TextStyle(
    fontSize: 80,
    color: Colors.blue,
    fontFamily: 'Courier',
  ),
)
```
<img width="201" alt="image" src="https://user-images.githubusercontent.com/41172064/156420516-a8a5d905-9f4b-4878-b288-0caf100207b1.png">

**Comment by yuhao-nyc** [comment]
ah ok. Is there any other workaround for this besides changing the font?

**Comment by h65wang** [comment]
If you have a particular font you like to use, you can examine all digits in that font, and then hardcode some padding into certain digits. This won't be a general solution, because the padding values will differ for each font, so you should fork the project and make your own modifications.

**Comment by h65wang** [comment]
I just took a closer look at this and there seems to be a fix. I'm gonna create a new release in a moment.

**Comment by h65wang** [comment]
I just released a fix in `v0.2.4`, please help test and report if your issue has been resolved. Thanks!

**Comment by yuhao-nyc** [comment]
<img width="424" alt="Screen Shot 2022-03-08 at 12 34 18 PM" src="https://user-images.githubusercontent.com/4121735/157293494-54162ca2-a06f-451f-8854-4e0d22879143.png">

@h65wang nope after update to `v0.2.4` still looks the same
FYI. The screenshot was taken in Chrome

**Comment by yuhao-nyc** [comment]
Following up on this. I did noticed the issue was fixed on our mobile app just not the web app

**Comment by h65wang** [comment]
@yuhao-nyc Please check out this web app that used this plugin: https://d1qjxjz3vso8bm.cloudfront.net/#/

I don't notice any issues with number 1, is that what you are seeing as well?

<img width="169" alt="image" src="https://user-images.githubusercontent.com/41172064/159983646-74c9bd64-d6a7-40a3-865d-51d4eb6e7990.png">

If not, please let me know your environment: OS and browser. Thanks.

**Comment by yuhao-nyc** [comment]
Hey @h65wang apologize for the late response. It does looks fine on the you post above but in my project it's still acting funny. i dont know if it's because the font i use. I'm running the app on my MBP + Chrome
<img width="1067" alt="Screen Shot 2022-05-04 at 2 08 21 PM" src="https://user-images.githubusercontent.com/4121735/166783697-7b609c0b-3a4b-44a7-bb6e-1f93150c7e49.png">
.

**Comment by yuhao-nyc** [comment]
I did more research today it turns out to be the font. Even without the animation it's still showin the extra spacing. So closing it
