### ISSUE TITLE
Tween animation when adding digits

### ISSUE THREAD

**Issue by SimonVillage** [h65wang/flutter-animated-counter#9]
I was wondering if it would be easy to add a tween animation if the width is expanding (a digit is added).
There is already a tween animation for the "-". To implement it like in the video below, we would need to know the width of the number and the width after adding a digit if I am not wrong.

Any suggestion?

https://user-images.githubusercontent.com/1446685/169464500-83e6ffe1-bd25-48b4-a7a7-9121c1322b18.mp4

**Comment by h65wang** [comment]
In version 0.3.0, I added a `hideLeadingZeroes` property. Useful when number of digits is expected to increase (e.g. going from 99 to 100), you can use `wholeDigits: 3` to pad a leading zero, and use this new property to hide padded zeroes. Although invisible, they help deliver a smoother animation when new digits appear.
